export type SeedTopic = {
  slug: string
  label: string
  category: string
  description: string
  minLevel: string
  maxLevel: string
  communicativeFunctions: string[]
  emotionalFunctions: string[]
  relatedConstructionFns: string[]
  iconKey: string
  displayOrder: number
  metadata: Record<string, unknown>
}

export type SeedWritingGoal = {
  slug: string
  label: string
  description: string
  communicativePurpose: string
  recommendedExerciseTypes: string[]
  relatedConstructionFns: string[]
  minLevel: string
  maxLevel: string
  displayOrder: number
  metadata: Record<string, unknown>
}

export type SeedLearningPath = {
  slug: string
  label: string
  description: string
  displayOrder: number
  metadata: Record<string, unknown>
  stages: Array<{
    slug: string
    label: string
    description: string
    stageOrder: number
    targetExpressionAbility: string
    prerequisiteConstructionTypes: string[]
    recommendedExerciseTypes: string[]
    nextRecommendedStageSlug?: string
    metadata: Record<string, unknown>
  }>
}

export const TEACHING_CATALOG_VERSION = '2026.05.teaching-kb.v1'

export const seedLearningPaths: SeedLearningPath[] = [
  {
    slug: 'expression-growth',
    label: 'Expression Growth Path',
    description: 'A lightweight path from clear sentence expression to confident intercultural communication.',
    displayOrder: 10,
    metadata: {
      principle: 'Help students express meaning better, not diagnose level automatically.',
      manually_selected_level: true,
    },
    stages: [
      {
        slug: 'clear-sentence-expression',
        label: 'Clear Sentence Expression',
        description: 'Build accurate, useful sentences with phrase and collocation support.',
        stageOrder: 10,
        targetExpressionAbility: 'clear sentence expression',
        prerequisiteConstructionTypes: ['phrase', 'collocation'],
        recommendedExerciseTypes: ['single_sentence_translation', 'construction_guided_continuation'],
        nextRecommendedStageSlug: 'explain-reasons',
        metadata: { ability_tags: ['clarity', 'natural phrasing'] },
      },
      {
        slug: 'explain-reasons',
        label: 'Explain Reasons',
        description: 'Use cause, purpose, and explanation patterns to make meaning easy to follow.',
        stageOrder: 20,
        targetExpressionAbility: 'explaining reasons',
        prerequisiteConstructionTypes: ['sentence_pattern', 'discourse_pattern'],
        recommendedExerciseTypes: ['gap_continuation', 'single_sentence_translation'],
        nextRecommendedStageSlug: 'describe-emotions',
        metadata: { ability_tags: ['because', 'so that', 'reason'] },
      },
      {
        slug: 'describe-emotions',
        label: 'Describe Emotions',
        description: 'Move beyond simple feeling words into believable emotional turns.',
        stageOrder: 30,
        targetExpressionAbility: 'describing emotions naturally',
        prerequisiteConstructionTypes: ['phrase', 'sentence_pattern'],
        recommendedExerciseTypes: ['micro_continuation', 'long_continuation'],
        nextRecommendedStageSlug: 'connect-ideas',
        metadata: { ability_tags: ['emotion', 'realization', 'tone'] },
      },
      {
        slug: 'connect-ideas',
        label: 'Connect Ideas',
        description: 'Use transitions and discourse patterns to control logic and narrative flow.',
        stageOrder: 40,
        targetExpressionAbility: 'connecting ideas smoothly',
        prerequisiteConstructionTypes: ['discourse_pattern'],
        recommendedExerciseTypes: ['gap_continuation', 'construction_guided_continuation'],
        nextRecommendedStageSlug: 'compare-cultures',
        metadata: { ability_tags: ['transition', 'contrast', 'flow'] },
      },
      {
        slug: 'compare-cultures',
        label: 'Compare Perspectives',
        description: 'Compare habits, values, and youth life across cultures with respect and nuance.',
        stageOrder: 50,
        targetExpressionAbility: 'comparing cultures and youth life',
        prerequisiteConstructionTypes: ['intercultural_expression', 'discourse_pattern'],
        recommendedExerciseTypes: ['construction_guided_continuation', 'single_sentence_translation'],
        nextRecommendedStageSlug: 'repair-misunderstanding',
        metadata: { ability_tags: ['comparison', 'respect', 'intercultural explanation'] },
      },
      {
        slug: 'repair-misunderstanding',
        label: 'Repair Misunderstanding',
        description: 'Clarify intention, soften disagreement, apologize, and protect relationships.',
        stageOrder: 60,
        targetExpressionAbility: 'handling misunderstanding',
        prerequisiteConstructionTypes: ['communicative_expression'],
        recommendedExerciseTypes: ['gap_continuation', 'micro_continuation'],
        nextRecommendedStageSlug: 'narrative-flow',
        metadata: { ability_tags: ['repair', 'tone', 'clarification'] },
      },
      {
        slug: 'narrative-flow',
        label: 'Build Narrative Flow',
        description: 'Control action, reaction, reflection, and ending in continuation writing.',
        stageOrder: 70,
        targetExpressionAbility: 'building narrative flow',
        prerequisiteConstructionTypes: ['sentence_pattern', 'discourse_pattern'],
        recommendedExerciseTypes: ['action_chain_continuation', 'long_continuation'],
        nextRecommendedStageSlug: 'confident-intercultural-expression',
        metadata: { ability_tags: ['action chain', 'reflection', 'ending'] },
      },
      {
        slug: 'confident-intercultural-expression',
        label: 'Confident Intercultural Expression',
        description: 'Explain modern Chinese youth life and personal identity in natural English.',
        stageOrder: 80,
        targetExpressionAbility: 'communicating across cultures with confidence',
        prerequisiteConstructionTypes: ['intercultural_expression', 'communicative_expression', 'discourse_pattern'],
        recommendedExerciseTypes: ['long_continuation', 'construction_guided_continuation'],
        metadata: { ability_tags: ['identity', 'modern youth life', 'confidence'] },
      },
    ],
  },
]

export const seedTopics: SeedTopic[] = [
  {
    slug: 'festival-family',
    label: 'Festivals and Family',
    category: 'culture',
    description: 'Explain family gatherings, festival customs, food, and warmth in everyday Chinese life.',
    minLevel: 'junior',
    maxLevel: 'senior',
    communicativeFunctions: ['cultural_explanation', 'sharing_memory', 'comparison'],
    emotionalFunctions: ['warmth', 'gratitude', 'belonging'],
    relatedConstructionFns: ['explanation', 'cause_result', 'emotional_response', 'comparison'],
    iconKey: 'sparkles',
    displayOrder: 10,
    metadata: {
      scene_types: ['family_dinner', 'festival', 'school_exchange'],
      level_tags: ['junior', 'senior'],
      recommended: true,
    },
  },
  {
    slug: 'food-hospitality',
    label: 'Food and Hospitality',
    category: 'daily_life',
    description: 'Guide a guest through food, table manners, taste, invitation, and care.',
    minLevel: 'junior',
    maxLevel: 'senior',
    communicativeFunctions: ['invitation', 'explanation', 'showing_respect'],
    emotionalFunctions: ['warmth', 'curiosity', 'comfort'],
    relatedConstructionFns: ['invitation_or_offer', 'action_sequence', 'cultural_explanation'],
    iconKey: 'leaf',
    displayOrder: 20,
    metadata: {
      scene_types: ['family_dinner', 'restaurant', 'tea_house'],
      level_tags: ['junior', 'senior'],
    },
  },
  {
    slug: 'school-exchange',
    label: 'School Exchange',
    category: 'school',
    description: 'Communicate with classmates, visitors, and teachers in a cross-cultural school setting.',
    minLevel: 'junior',
    maxLevel: 'senior',
    communicativeFunctions: ['clarification', 'encouragement', 'invitation', 'reflection'],
    emotionalFunctions: ['confidence', 'empathy', 'patience'],
    relatedConstructionFns: ['communication', 'clarification', 'action_sequence', 'reflection'],
    iconKey: 'book-open',
    displayOrder: 30,
    metadata: {
      scene_types: ['classroom', 'school_exchange', 'online_chat'],
      level_tags: ['junior', 'senior'],
      recommended: true,
    },
  },
  {
    slug: 'travel-directions',
    label: 'Travel and Directions',
    category: 'daily_life',
    description: 'Help someone move through a place, solve a small problem, and understand local behavior.',
    minLevel: 'junior',
    maxLevel: 'senior',
    communicativeFunctions: ['guidance', 'clarification', 'problem_solving'],
    emotionalFunctions: ['patience', 'relief', 'confidence'],
    relatedConstructionFns: ['action_sequence', 'cause_result', 'clarification'],
    iconKey: 'map',
    displayOrder: 40,
    metadata: {
      scene_types: ['travel', 'museum', 'street'],
      level_tags: ['junior', 'senior'],
    },
  },
  {
    slug: 'art-and-heritage',
    label: 'Art and Heritage',
    category: 'culture',
    description: 'Describe museums, crafts, calligraphy, paintings, and the meaning behind cultural objects.',
    minLevel: 'senior',
    maxLevel: 'senior',
    communicativeFunctions: ['description', 'cultural_explanation', 'reflection'],
    emotionalFunctions: ['curiosity', 'respect', 'realization'],
    relatedConstructionFns: ['scene_description', 'cultural_explanation', 'reflection', 'comparison'],
    iconKey: 'palette',
    displayOrder: 50,
    metadata: {
      scene_types: ['museum', 'art_room', 'garden'],
      level_tags: ['senior'],
    },
  },
  {
    slug: 'friendship-empathy',
    label: 'Friendship and Empathy',
    category: 'relationship',
    description: 'Express care, repair misunderstanding, encourage a friend, and manage emotional turns.',
    minLevel: 'junior',
    maxLevel: 'senior',
    communicativeFunctions: ['encouragement', 'apology', 'disagreement_softening', 'comfort'],
    emotionalFunctions: ['empathy', 'regret', 'comfort', 'confidence'],
    relatedConstructionFns: ['emotional_response', 'relationship_repair', 'contrast_or_turn'],
    iconKey: 'heart-handshake',
    displayOrder: 60,
    metadata: {
      scene_types: ['classroom', 'online_chat', 'peer_to_peer'],
      level_tags: ['junior', 'senior'],
      recommended: true,
    },
  },
  {
    slug: 'study-pressure',
    label: 'Study Pressure and Learning Methods',
    category: 'modern_youth_life',
    description: 'Talk about homework, exams, learning routines, stress, and practical study habits with international peers.',
    minLevel: 'junior',
    maxLevel: 'senior',
    communicativeFunctions: ['reflection', 'explanation', 'encouragement', 'comparison'],
    emotionalFunctions: ['pressure', 'confidence', 'relief', 'empathy'],
    relatedConstructionFns: ['reflection', 'cause_result', 'emotional_response', 'comparison'],
    iconKey: 'notebook-pen',
    displayOrder: 70,
    metadata: {
      intercultural_usefulness: 'Helps students explain real school pressure without sounding negative or defensive.',
      real_life_situations: ['exchange_student_chat', 'class_discussion', 'online_peer_support'],
      student_role: 'student sharing learning experience',
      audience: 'international classmate or roommate',
      suitable_exercise_types: ['micro_continuation', 'long_continuation', 'single_sentence_translation'],
      level_tags: ['junior', 'senior'],
      recommended: true,
    },
  },
  {
    slug: 'university-internship',
    label: 'University Life and Internships',
    category: 'career_and_future',
    description: 'Discuss majors, campus life, internships, interviews, career choices, and uncertainty about the future.',
    minLevel: 'senior',
    maxLevel: 'senior',
    communicativeFunctions: ['explaining_goals', 'comparison', 'clarification', 'reflection'],
    emotionalFunctions: ['uncertainty', 'hope', 'pressure', 'confidence'],
    relatedConstructionFns: ['reflection', 'comparison', 'clarification', 'cause_result'],
    iconKey: 'briefcase-business',
    displayOrder: 80,
    metadata: {
      intercultural_usefulness: 'Supports realistic conversations about future planning and different expectations across countries.',
      real_life_situations: ['roommate_conversation', 'career_fair', 'internship_group_chat'],
      student_role: 'college student explaining choices and concerns',
      audience: 'international peer or mentor',
      suitable_exercise_types: ['long_continuation', 'construction_guided_continuation', 'micro_continuation'],
      level_tags: ['senior'],
      recommended: true,
    },
  },
  {
    slug: 'ai-learning-tools',
    label: 'AI Tools and Learning',
    category: 'digital_life_and_ai',
    description: 'Explain how students use AI for vocabulary, writing, planning, and self-study while discussing boundaries.',
    minLevel: 'senior',
    maxLevel: 'senior',
    communicativeFunctions: ['clarification', 'opinion_softening', 'comparison', 'explanation'],
    emotionalFunctions: ['curiosity', 'confidence', 'uncertainty'],
    relatedConstructionFns: ['clarification', 'comparison', 'cause_result', 'disagreement_softening'],
    iconKey: 'bot',
    displayOrder: 90,
    metadata: {
      intercultural_usefulness: 'Lets students discuss technology use without sounding defensive or overexcited.',
      real_life_situations: ['class_project', 'study_group', 'teacher_conversation'],
      student_role: 'student explaining responsible AI use',
      audience: 'teacher, classmate, or international teammate',
      suitable_exercise_types: ['gap_continuation', 'single_sentence_translation', 'micro_continuation'],
      level_tags: ['senior'],
      recommended: true,
    },
  },
  {
    slug: 'animation-games-media',
    label: 'Animation, Games, and Media',
    category: 'animation_games_media',
    description: 'Recommend a favorite animation, game, film, song, or online creator and explain why it matters.',
    minLevel: 'junior',
    maxLevel: 'senior',
    communicativeFunctions: ['sharing_preferences', 'recommendation', 'cultural_explanation', 'comparison'],
    emotionalFunctions: ['excitement', 'belonging', 'curiosity', 'respect'],
    relatedConstructionFns: ['invitation_or_offer', 'explanation', 'comparison', 'emotional_response'],
    iconKey: 'gamepad-2',
    displayOrder: 100,
    metadata: {
      intercultural_usefulness: 'Connects Chinese youth interests with global youth culture through concrete recommendations.',
      real_life_situations: ['online_chat', 'club_activity', 'dorm_conversation'],
      student_role: 'fan recommending and explaining a media work',
      audience: 'international friend with different media background',
      suitable_exercise_types: ['micro_continuation', 'single_sentence_translation', 'construction_guided_continuation'],
      level_tags: ['junior', 'senior'],
      recommended: true,
    },
  },
  {
    slug: 'milk-tea-food-delivery',
    label: 'Milk Tea, Coffee, and Food Delivery',
    category: 'drinks_food_daily_consumption',
    description: 'Explain drink habits, ordering apps, delivery culture, small treats, and social routines among students.',
    minLevel: 'junior',
    maxLevel: 'senior',
    communicativeFunctions: ['explanation', 'invitation', 'comparison', 'daily_life_description'],
    emotionalFunctions: ['warmth', 'comfort', 'curiosity'],
    relatedConstructionFns: ['invitation_or_offer', 'action_sequence', 'explanation', 'comparison'],
    iconKey: 'cup-soda',
    displayOrder: 110,
    metadata: {
      intercultural_usefulness: 'Shows that everyday consumption can reveal social habits, convenience, and youth culture.',
      real_life_situations: ['after_class', 'city_walk', 'dorm_ordering'],
      student_role: 'student explaining a daily habit or inviting a friend',
      audience: 'international friend new to Chinese city life',
      suitable_exercise_types: ['action_chain_continuation', 'micro_continuation', 'single_sentence_translation'],
      level_tags: ['junior', 'senior'],
    },
  },
  {
    slug: 'city-commuting-daily-life',
    label: 'City Life and Commuting',
    category: 'city_life_and_travel',
    description: 'Describe subways, buses, cycling, night markets, city walks, and how daily movement shapes life.',
    minLevel: 'junior',
    maxLevel: 'senior',
    communicativeFunctions: ['guidance', 'description', 'comparison', 'problem_solving'],
    emotionalFunctions: ['patience', 'relief', 'warmth', 'curiosity'],
    relatedConstructionFns: ['action_sequence', 'scene_description', 'cause_result', 'clarification'],
    iconKey: 'train-front',
    displayOrder: 120,
    metadata: {
      intercultural_usefulness: 'Helps students introduce modern Chinese cities through daily routines, not tourist slogans.',
      real_life_situations: ['commuting_help', 'travel_plan', 'city_walk'],
      student_role: 'local student guide',
      audience: 'visitor, exchange student, or online friend',
      suitable_exercise_types: ['action_chain_continuation', 'long_continuation', 'gap_continuation'],
      level_tags: ['junior', 'senior'],
    },
  },
  {
    slug: 'teamwork-direct-feedback',
    label: 'Teamwork and Direct Feedback',
    category: 'intercultural_misunderstanding_repair',
    description: 'Handle group projects, different feedback styles, responsibility, apology, and repair after misunderstanding.',
    minLevel: 'senior',
    maxLevel: 'senior',
    communicativeFunctions: ['clarification', 'apology', 'disagreement_softening', 'repair'],
    emotionalFunctions: ['regret', 'respect', 'patience', 'trust'],
    relatedConstructionFns: ['relationship_repair', 'clarification', 'disagreement_softening', 'contrast_or_turn'],
    iconKey: 'users',
    displayOrder: 130,
    metadata: {
      intercultural_usefulness: 'Trains students to manage real communication friction in multicultural teamwork.',
      real_life_situations: ['group_project', 'club_activity', 'online_meeting'],
      student_role: 'team member repairing meaning and trust',
      audience: 'international teammate',
      suitable_exercise_types: ['gap_continuation', 'micro_continuation', 'single_sentence_translation'],
      level_tags: ['senior'],
      recommended: true,
    },
  },
  {
    slug: 'family-expectations-dreams',
    label: 'Family Expectations and Personal Dreams',
    category: 'family_identity_growth',
    description: 'Explain family hopes, personal choices, career dreams, respect, pressure, and growing independence.',
    minLevel: 'senior',
    maxLevel: 'senior',
    communicativeFunctions: ['reflection', 'explanation', 'comparison', 'emotional_expression'],
    emotionalFunctions: ['respect', 'pressure', 'hope', 'empathy'],
    relatedConstructionFns: ['reflection', 'emotional_response', 'comparison', 'cause_result'],
    iconKey: 'sunrise',
    displayOrder: 140,
    metadata: {
      intercultural_usefulness: 'Helps students explain family values and personal agency with nuance.',
      real_life_situations: ['roommate_conversation', 'essay_reflection', 'career_discussion'],
      student_role: 'student explaining a personal choice respectfully',
      audience: 'international roommate or classmate',
      suitable_exercise_types: ['long_continuation', 'construction_guided_continuation', 'micro_continuation'],
      level_tags: ['senior'],
      recommended: true,
    },
  },
  {
    slug: 'online-friendship-communication',
    label: 'Online Friendship and Communication',
    category: 'friendship_online_communication',
    description: 'Talk about messaging, tone, online communities, emojis, voice notes, and keeping friendship across distance.',
    minLevel: 'junior',
    maxLevel: 'senior',
    communicativeFunctions: ['clarification', 'sharing_preferences', 'repair', 'emotional_expression'],
    emotionalFunctions: ['belonging', 'care', 'misunderstanding', 'comfort'],
    relatedConstructionFns: ['clarification', 'relationship_repair', 'emotional_response', 'comparison'],
    iconKey: 'message-circle-heart',
    displayOrder: 150,
    metadata: {
      intercultural_usefulness: 'Supports everyday intercultural friendship where tone and digital habits can be misunderstood.',
      real_life_situations: ['online_chat', 'gaming_chat', 'long_distance_friendship'],
      student_role: 'friend clarifying tone or sharing online habits',
      audience: 'international online friend',
      suitable_exercise_types: ['micro_continuation', 'gap_continuation', 'single_sentence_translation'],
      level_tags: ['junior', 'senior'],
    },
  },
  {
    slug: 'global-youth-culture',
    label: 'Global Youth Culture',
    category: 'global_youth_culture',
    description: 'Compare music, sports, hobbies, trends, social media habits, and what young people care about.',
    minLevel: 'junior',
    maxLevel: 'senior',
    communicativeFunctions: ['comparison', 'asking_respectfully', 'sharing_preferences', 'reflection'],
    emotionalFunctions: ['curiosity', 'respect', 'confidence'],
    relatedConstructionFns: ['comparison', 'invitation_or_offer', 'clarification', 'reflection'],
    iconKey: 'globe-2',
    displayOrder: 160,
    metadata: {
      intercultural_usefulness: 'Moves intercultural communication from performance to mutual youth conversation.',
      real_life_situations: ['club_chat', 'short_video_discussion', 'sports_or_music_group'],
      student_role: 'peer comparing interests and values',
      audience: 'international peer',
      suitable_exercise_types: ['construction_guided_continuation', 'single_sentence_translation', 'micro_continuation'],
      level_tags: ['junior', 'senior'],
    },
  },
  {
    slug: 'tradition-in-modern-life',
    label: 'Tradition in Modern Life',
    category: 'traditional_culture_modern_life',
    description: 'Explain how young people keep, adapt, or question traditional values in modern daily life.',
    minLevel: 'senior',
    maxLevel: 'senior',
    communicativeFunctions: ['cultural_explanation', 'reflection', 'comparison', 'balancing_views'],
    emotionalFunctions: ['respect', 'realization', 'belonging', 'curiosity'],
    relatedConstructionFns: ['cultural_explanation', 'contrast_or_turn', 'reflection', 'comparison'],
    iconKey: 'sprout',
    displayOrder: 170,
    metadata: {
      intercultural_usefulness: 'Connects culture with real student choices instead of old-fashioned display topics.',
      real_life_situations: ['family_story', 'class_discussion', 'festival_with_friends'],
      student_role: 'student explaining continuity and change',
      audience: 'international friend or teacher',
      suitable_exercise_types: ['long_continuation', 'gap_continuation', 'construction_guided_continuation'],
      level_tags: ['senior'],
      recommended: true,
    },
  },
]

export const seedWritingGoals: SeedWritingGoal[] = [
  {
    slug: 'explain-culture',
    label: 'Explain Culture Clearly',
    description: 'Help another person understand a custom, object, or daily habit without sounding stiff.',
    communicativePurpose: 'Make unfamiliar cultural meaning concrete, respectful, and easy to follow.',
    recommendedExerciseTypes: ['long_continuation', 'construction_guided_continuation', 'single_sentence_translation'],
    relatedConstructionFns: ['explanation', 'cultural_explanation', 'cause_result', 'comparison'],
    minLevel: 'junior',
    maxLevel: 'senior',
    displayOrder: 10,
    metadata: { focus: ['intercultural_value', 'clarity', 'specific examples'] },
  },
  {
    slug: 'build-emotion',
    label: 'Show Emotional Change',
    description: 'Move from reaction to realization, comfort, relief, surprise, or gratitude.',
    communicativePurpose: 'Control emotional progression instead of naming feelings mechanically.',
    recommendedExerciseTypes: ['micro_continuation', 'long_continuation', 'gap_continuation'],
    relatedConstructionFns: ['emotional_response', 'contrast_or_turn', 'reflection'],
    minLevel: 'junior',
    maxLevel: 'senior',
    displayOrder: 20,
    metadata: { focus: ['emotional_arc', 'tone', 'small turning point'] },
  },
  {
    slug: 'guide-actions',
    label: 'Guide Actions Smoothly',
    description: 'Connect movement, reaction, and next steps in a clear action chain.',
    communicativePurpose: 'Make a scene easy to picture and easy to continue.',
    recommendedExerciseTypes: ['action_chain_continuation', 'micro_continuation', 'gap_continuation'],
    relatedConstructionFns: ['action_sequence', 'cause_result', 'physical_interaction'],
    minLevel: 'junior',
    maxLevel: 'senior',
    displayOrder: 30,
    metadata: { focus: ['sequence', 'reaction', 'visible detail'] },
  },
  {
    slug: 'soften-and-repair',
    label: 'Soften and Repair',
    description: 'Disagree, apologize, clarify, or comfort someone without sounding abrupt.',
    communicativePurpose: 'Protect relationship and meaning at the same time.',
    recommendedExerciseTypes: ['single_sentence_translation', 'micro_continuation', 'gap_continuation'],
    relatedConstructionFns: ['clarification', 'apology', 'disagreement_softening', 'relationship_repair'],
    minLevel: 'junior',
    maxLevel: 'senior',
    displayOrder: 40,
    metadata: { focus: ['politeness', 'tone', 'relationship'] },
  },
  {
    slug: 'compare-perspectives',
    label: 'Compare Perspectives',
    description: 'Explain similarities, differences, reasons, and personal reflection across cultures or choices.',
    communicativePurpose: 'Move beyond “A is different from B” into useful explanation.',
    recommendedExerciseTypes: ['construction_guided_continuation', 'single_sentence_translation', 'long_continuation'],
    relatedConstructionFns: ['comparison', 'contrast_or_turn', 'reflection', 'explanation'],
    minLevel: 'senior',
    maxLevel: 'senior',
    displayOrder: 50,
    metadata: { focus: ['comparison', 'balance', 'reflection'] },
  },
]
