import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()
const VERSION = 'high-value-confusing-constructions-2026-05-v1'

type Seed = {
  text: string
  meaning: string
  usage: string
  commonError: string
  example: string
  exampleZh: string
  tryZh: string
  type: string
  level: 'junior' | 'senior'
  functions: string[]
  risks: string[]
}

const seeds: Seed[] = [
  {
    text: 'not too...to...',
    meaning: '并不是太……以至于不能……；还不至于不能……',
    usage: 'Used to say something is still possible, often to encourage action or reduce worry.',
    commonError: 'Many students translate it as “太……不能……”, but the not changes the meaning.',
    example: 'You are not too young to express your own opinion.',
    exampleZh: '你并不是小到不能表达自己的观点。',
    tryZh: '你并不是紧张到不能和外国同学解释清楚。',
    type: 'special_negative_structure',
    level: 'senior',
    functions: ['encouragement', 'clarification', 'confidence'],
    risks: ['negation_scope', 'word_order', 'literal_translation'],
  },
  {
    text: 'never too...to...',
    meaning: '再……也不为过；永远不会太……而不能……',
    usage: 'Used to emphasize that an action is always worth doing.',
    commonError: 'Do not read it as “永远太……不能……”. It usually has a positive meaning.',
    example: 'It is never too late to learn how to listen better.',
    exampleZh: '学习更好地倾听永远都不晚。',
    tryZh: '学习用更温和的方式表达不同意见，什么时候都不晚。',
    type: 'special_negative_structure',
    level: 'junior',
    functions: ['encouragement', 'reflection'],
    risks: ['negation_scope', 'literal_translation'],
  },
  {
    text: 'nothing but...',
    meaning: '只有；只是',
    usage: 'Used to narrow the meaning strongly to one thing.',
    commonError: 'It does not mean “什么都没有，但是……”. The phrase after but is the only thing.',
    example: 'His words showed nothing but respect for the local custom.',
    exampleZh: '他的话只表现出对当地习俗的尊重。',
    tryZh: '她的建议只是为了让小组合作更顺利。',
    type: 'emphasis_negative_structure',
    level: 'senior',
    functions: ['emphasis', 'clarification'],
    risks: ['literal_translation', 'misreading_but'],
  },
  {
    text: 'nothing if not...',
    meaning: '非常；极其；再……不过',
    usage: 'Used to strongly describe a quality, often in a slightly formal or witty tone.',
    commonError: 'It is not a conditional “如果不……就没有……”.',
    example: 'The discussion was nothing if not honest.',
    exampleZh: '这场讨论非常坦诚。',
    tryZh: '这次跨文化小组合作非常有挑战性。',
    type: 'emphasis_negative_structure',
    level: 'senior',
    functions: ['emphasis', 'evaluation'],
    risks: ['literal_translation', 'tone'],
  },
  {
    text: 'nothing less than...',
    meaning: '完全是；简直是；不少于',
    usage: 'Used to emphasize that something is very strong or impressive.',
    commonError: 'Check the context: it can mean strong emphasis, not only a number comparison.',
    example: 'Her courage was nothing less than inspiring.',
    exampleZh: '她的勇气简直令人振奋。',
    tryZh: '第一次用英语解释家乡文化的经历简直令人难忘。',
    type: 'emphasis_negative_structure',
    level: 'senior',
    functions: ['emphasis', 'emotional_expression'],
    risks: ['literal_translation', 'collocation'],
  },
  {
    text: 'nothing short of...',
    meaning: '简直就是；无异于；非常……',
    usage: 'Used to strongly emphasize an impressive, extreme, or surprising quality.',
    commonError: 'Do not use it for ordinary small things; it carries strong emphasis.',
    example: 'The experience was nothing short of unforgettable.',
    exampleZh: '这段经历简直令人难忘。',
    tryZh: '第一次和外国学生一起完成纪录片项目的经历令人惊叹。',
    type: 'emphasis_negative_structure',
    level: 'senior',
    functions: ['emphasis', 'emotional_expression'],
    risks: ['overuse', 'tone', 'collocation'],
  },
  {
    text: "couldn't care less",
    meaning: '一点也不在乎',
    usage: 'Used to say someone does not care at all, usually informal and strong.',
    commonError: 'Do not say “could care less” in careful learning contexts; it causes confusion.',
    example: "He couldn't care less about winning; he only wanted the team to learn something.",
    exampleZh: '他一点也不在乎输赢；他只希望团队能学到东西。',
    tryZh: '她一点也不在乎别人笑她的口音，她只想把意思说明白。',
    type: 'idiom_teachable',
    level: 'senior',
    functions: ['attitude', 'emphasis'],
    risks: ['fixed_expression', 'negation_scope'],
  },
  {
    text: 'more than just...',
    meaning: '不只是……；远不止……',
    usage: 'Used to deepen meaning and show that something has extra value.',
    commonError: 'Do not stop at “more than” as only a number comparison.',
    example: 'The project was more than just a school assignment.',
    exampleZh: '这个项目不只是一次学校作业。',
    tryZh: '这次交流不只是练习英语，也是理解不同生活方式的机会。',
    type: 'comparison_emphasis',
    level: 'junior',
    functions: ['deepening_meaning', 'reflection'],
    risks: ['literal_translation', 'incomplete_meaning'],
  },
  {
    text: 'no more than...',
    meaning: '仅仅；只有',
    usage: 'Used to emphasize that a number or degree is small.',
    commonError: 'Do not confuse it with “not more than”; no more than sounds more emphatic.',
    example: 'The talk lasted no more than ten minutes, but it changed my view.',
    exampleZh: '这次谈话只有十分钟，却改变了我的看法。',
    tryZh: '我们只用了五分钟，就化解了那个误会。',
    type: 'comparison_limit',
    level: 'senior',
    functions: ['limitation', 'contrast'],
    risks: ['comparison_confusion', 'tone'],
  },
  {
    text: 'not more than...',
    meaning: '不超过',
    usage: 'Used neutrally to set a maximum number or amount.',
    commonError: 'It is usually a neutral limit, weaker than “no more than”.',
    example: 'Please write not more than 120 words for this response.',
    exampleZh: '这次回答请不要超过 120 个词。',
    tryZh: '你的续写不要超过 100 个词，但要表达清楚情绪变化。',
    type: 'comparison_limit',
    level: 'junior',
    functions: ['limitation', 'instruction'],
    risks: ['comparison_confusion'],
  },
  {
    text: 'no less than...',
    meaning: '多达；竟有；不少于',
    usage: 'Used to emphasize that a number, effort, or degree is surprisingly large.',
    commonError: 'Do not confuse it with “not less than”, which is more neutral.',
    example: 'No less than thirty students joined the intercultural workshop.',
    exampleZh: '竟有三十名学生参加了跨文化工作坊。',
    tryZh: '竟有二十个同学愿意帮交换生熟悉校园。',
    type: 'comparison_emphasis',
    level: 'senior',
    functions: ['emphasis', 'quantity'],
    risks: ['comparison_confusion', 'tone'],
  },
  {
    text: 'rather than...',
    meaning: '而不是；宁愿……而不……',
    usage: 'Used to choose one action or idea over another.',
    commonError: 'Keep the forms parallel: rather than doing..., not rather than do/doing randomly.',
    example: 'Rather than judging the custom quickly, I tried to ask why it mattered.',
    exampleZh: '我没有急着评价这个习俗，而是试着询问它为什么重要。',
    tryZh: '我没有直接反驳他，而是先解释我的想法。',
    type: 'contrast_choice',
    level: 'junior',
    functions: ['contrast', 'choice', 'softening'],
    risks: ['parallel_structure', 'literal_translation'],
  },
  {
    text: 'other than...',
    meaning: '除了……之外',
    usage: 'Used to exclude something or ask about alternatives.',
    commonError: 'Do not confuse it with “rather than”; other than means except.',
    example: 'Other than a few words, we had no shared language at first.',
    exampleZh: '起初，除了几个词之外，我们没有共同语言。',
    tryZh: '除了语气有点直接之外，他的建议其实很有帮助。',
    type: 'exception_structure',
    level: 'senior',
    functions: ['exception', 'clarification'],
    risks: ['confusable_phrase', 'preposition'],
  },
  {
    text: 'anything but...',
    meaning: '绝不是；一点也不……',
    usage: 'Used to strongly deny a description.',
    commonError: 'It means the opposite of the adjective after but, not “任何东西但是”.',
    example: 'The conversation was anything but easy.',
    exampleZh: '这次谈话一点也不容易。',
    tryZh: '第一次用英语道歉一点也不轻松。',
    type: 'negative_emphasis',
    level: 'senior',
    functions: ['emphasis', 'evaluation'],
    risks: ['literal_translation', 'negation_scope'],
  },
  {
    text: 'all but...',
    meaning: '几乎；差不多',
    usage: 'Used to say something is almost complete or almost true.',
    commonError: 'It usually means “almost”, not “所有除了”.',
    example: 'The misunderstanding was all but solved after her explanation.',
    exampleZh: '她解释之后，误会几乎解决了。',
    tryZh: '经过那次谈话，我们几乎达成了一致。',
    type: 'near_completion',
    level: 'senior',
    functions: ['result', 'evaluation'],
    risks: ['literal_translation', 'confusable_phrase'],
  },
  {
    text: 'none other than...',
    meaning: '正是；不是别人，正是……',
    usage: 'Used to reveal or emphasize a surprising person or thing.',
    commonError: 'Use it only when the identity is worth emphasizing.',
    example: 'The student who helped me was none other than the quiet boy from my group.',
    exampleZh: '帮助我的学生正是我们小组里那个安静的男孩。',
    tryZh: '提出最好解决办法的人，正是那个一开始最沉默的同学。',
    type: 'emphasis_identity',
    level: 'senior',
    functions: ['emphasis', 'revelation'],
    risks: ['overuse', 'word_order'],
  },
  {
    text: 'not so much...as...',
    meaning: '与其说是……不如说是……',
    usage: 'Used to correct or refine how something should be understood.',
    commonError: 'Keep the two parts parallel and do not translate word by word.',
    example: 'The problem was not so much language as tone.',
    exampleZh: '问题与其说是语言，不如说是语气。',
    tryZh: '这次误会与其说是文化差异，不如说是解释不够清楚。',
    type: 'comparison_reframing',
    level: 'senior',
    functions: ['reframing', 'analysis'],
    risks: ['parallel_structure', 'literal_translation'],
  },
  {
    text: 'the more..., the more...',
    meaning: '越……越……',
    usage: 'Used to show two things changing together.',
    commonError: 'Do not write “more..., more...”; both clauses need the + comparative.',
    example: 'The more we talked, the more comfortable we felt.',
    exampleZh: '我们聊得越多，就越觉得自在。',
    tryZh: '我们越了解彼此的生活，就越容易避免误会。',
    type: 'comparative_correlation',
    level: 'junior',
    functions: ['cause_effect', 'development'],
    risks: ['word_order', 'missing_the'],
  },
  {
    text: 'more and more...',
    meaning: '越来越……',
    usage: 'Used to describe gradual growth or change.',
    commonError: 'Use “more and more + adjective/noun”, but for short adjectives use “-er and -er”.',
    example: 'I became more and more confident when I learned to explain my ideas clearly.',
    exampleZh: '当我学会清楚解释想法时，我变得越来越自信。',
    tryZh: '通过小组合作，我越来越愿意主动表达观点。',
    type: 'comparative_development',
    level: 'junior',
    functions: ['development', 'emotion_change'],
    risks: ['comparative_form', 'collocation'],
  },
  {
    text: 'better than expected',
    meaning: '比预期更好',
    usage: 'Used to evaluate a result that turned out positively.',
    commonError: 'Do not add “my expected”; say better than expected or better than I expected.',
    example: 'The conversation went better than expected.',
    exampleZh: '这次谈话比预期更顺利。',
    tryZh: '我们的英文展示比预期更成功。',
    type: 'comparative_evaluation',
    level: 'junior',
    functions: ['evaluation', 'relief'],
    risks: ['collocation', 'literal_translation'],
  },
  {
    text: 'easier said than done',
    meaning: '说起来容易做起来难',
    usage: 'Used to admit that an idea sounds simple but is hard in practice.',
    commonError: 'Use it as a fixed expression; do not change the word order.',
    example: 'Respecting every opinion is easier said than done.',
    exampleZh: '尊重每一种意见说起来容易做起来难。',
    tryZh: '在压力下保持耐心说起来容易做起来难。',
    type: 'idiom_teachable',
    level: 'junior',
    functions: ['reflection', 'difficulty'],
    risks: ['fixed_expression', 'word_order'],
  },
  {
    text: 'nothing is more important than...',
    meaning: '没有什么比……更重要',
    usage: 'Used to emphasize the highest priority.',
    commonError: 'Avoid adding another negative after it; one negative is enough.',
    example: 'Nothing is more important than keeping the conversation respectful.',
    exampleZh: '没有什么比让谈话保持尊重更重要。',
    tryZh: '没有什么比理解对方真正的意思更重要。',
    type: 'comparative_emphasis',
    level: 'junior',
    functions: ['value_focus', 'emphasis'],
    risks: ['double_negative', 'word_order'],
  },
  {
    text: 'as...as...',
    meaning: '和……一样……',
    usage: 'Used to show equal degree in comparison.',
    commonError: 'Use the adjective/adverb base form, not comparative form.',
    example: 'Her explanation was as clear as a simple picture.',
    exampleZh: '她的解释像一幅简单的图一样清楚。',
    tryZh: '这次活动和我想象的一样有意义。',
    type: 'comparison_equal',
    level: 'junior',
    functions: ['comparison', 'description'],
    risks: ['comparative_form', 'word_order'],
  },
  {
    text: 'not as...as...',
    meaning: '不如……那么……',
    usage: 'Used to compare two things politely or realistically.',
    commonError: 'Use base adjective/adverb after as, not “more”.',
    example: 'The rule was not as simple as it first seemed.',
    exampleZh: '这条规则并不像一开始看起来那么简单。',
    tryZh: '这次误会并不像我们一开始想的那么严重。',
    type: 'comparison_negative_equal',
    level: 'junior',
    functions: ['comparison', 'softening'],
    risks: ['comparative_form', 'word_order'],
  },
  {
    text: 'far more...',
    meaning: '远比……更……',
    usage: 'Used to strengthen a comparison.',
    commonError: 'Use far before a comparative form, not before a base adjective.',
    example: 'Listening carefully is far more useful than arguing quickly.',
    exampleZh: '认真倾听远比急着争论更有用。',
    tryZh: '举真实例子远比直接翻译更有帮助。',
    type: 'comparison_intensifier',
    level: 'senior',
    functions: ['comparison', 'emphasis'],
    risks: ['comparative_form', 'collocation'],
  },
  {
    text: 'much less...',
    meaning: '更不用说……；更少……',
    usage: 'Used after a negative idea to say a stronger thing is even less likely.',
    commonError: 'Do not confuse it with “much more”; much less often follows a negative context.',
    example: 'I could hardly explain the rule in Chinese, much less in English.',
    exampleZh: '我用中文都很难解释这条规则，更不用说用英语了。',
    tryZh: '他连基本情况都不了解，更不用说给出公平评价了。',
    type: 'negative_comparison_extension',
    level: 'senior',
    functions: ['emphasis', 'limitation'],
    risks: ['context_requirement', 'literal_translation'],
  },
  {
    text: 'even better',
    meaning: '甚至更好；更妙的是',
    usage: 'Used to add a stronger positive point.',
    commonError: 'Use even before comparative forms, not before every adjective.',
    example: 'The plan worked, and even better, everyone felt included.',
    exampleZh: '这个计划奏效了，更妙的是，每个人都感到被包含其中。',
    tryZh: '我们完成了展示，更好的是，我们真正理解了彼此。',
    type: 'comparison_intensifier',
    level: 'junior',
    functions: ['addition', 'positive_evaluation'],
    risks: ['comparative_form', 'punctuation'],
  },
  {
    text: 'not only...but also...',
    meaning: '不仅……而且……',
    usage: 'Used to connect two parallel ideas and make an expression richer.',
    commonError: 'The two parts must be grammatically parallel.',
    example: 'The activity not only improved my English but also helped me understand another culture.',
    exampleZh: '这次活动不仅提高了我的英语，也帮助我理解了另一种文化。',
    tryZh: '这次合作不仅让我更自信，也让我学会了倾听。',
    type: 'addition_emphasis',
    level: 'junior',
    functions: ['addition', 'emphasis'],
    risks: ['parallel_structure', 'missing_also'],
  },
  {
    text: 'not because..., but because...',
    meaning: '不是因为……，而是因为……',
    usage: 'Used to correct the real reason behind an action or feeling.',
    commonError: 'Keep both clauses as reasons; do not mix because with a noun phrase awkwardly.',
    example: 'I stayed quiet not because I disagreed, but because I needed time to think.',
    exampleZh: '我保持沉默不是因为不同意，而是因为我需要时间思考。',
    tryZh: '我道歉不是因为我输了，而是因为我不想伤害朋友。',
    type: 'reason_correction',
    level: 'senior',
    functions: ['clarification', 'reasoning'],
    risks: ['parallel_structure', 'logic'],
  },
  {
    text: 'not that..., but that...',
    meaning: '不是说……，而是说……',
    usage: 'Used to clarify a subtle point or prevent misunderstanding.',
    commonError: 'This is a delicate structure; use complete that-clauses on both sides.',
    example: 'It is not that I dislike the idea, but that I worry about the timing.',
    exampleZh: '不是说我不喜欢这个想法，而是说我担心时机。',
    tryZh: '不是说我不尊重这个传统，而是说我还不完全理解它。',
    type: 'clarification_structure',
    level: 'senior',
    functions: ['clarification', 'softening'],
    risks: ['clause_structure', 'tone'],
  },
  {
    text: 'no matter how...',
    meaning: '无论多么……',
    usage: 'Used to show that something remains true under any degree.',
    commonError: 'Do not write “no matter how is it”; use normal statement order after how.',
    example: 'No matter how nervous I was, I tried to explain my idea clearly.',
    exampleZh: '无论我多紧张，我都努力把想法解释清楚。',
    tryZh: '无论问题多尴尬，我们都应该耐心沟通。',
    type: 'concession_structure',
    level: 'junior',
    functions: ['concession', 'persistence'],
    risks: ['word_order', 'literal_translation'],
  },
  {
    text: 'even if...',
    meaning: '即使……',
    usage: 'Used for an imagined condition that does not change the main idea.',
    commonError: 'Do not confuse it with even though, which usually refers to a real fact.',
    example: 'Even if my English is not perfect, I can still make my meaning clear.',
    exampleZh: '即使我的英语不完美，我仍然可以把意思说明白。',
    tryZh: '即使我们观点不同，也可以尊重地讨论。',
    type: 'concession_condition',
    level: 'junior',
    functions: ['concession', 'confidence'],
    risks: ['even_if_even_though', 'tense'],
  },
  {
    text: 'even though...',
    meaning: '尽管……',
    usage: 'Used for a real fact that contrasts with the main idea.',
    commonError: 'Do not use “but” immediately after even though in the same clause.',
    example: 'Even though the question sounded direct, I knew he meant no harm.',
    exampleZh: '尽管这个问题听起来直接，我知道他没有恶意。',
    tryZh: '尽管我们来自不同文化，我们仍然能成为朋友。',
    type: 'concession_fact',
    level: 'junior',
    functions: ['concession', 'relationship'],
    risks: ['double_conjunction', 'logic'],
  },
  {
    text: 'instead of...',
    meaning: '而不是；代替',
    usage: 'Used to replace one action with another.',
    commonError: 'After instead of, use a noun or -ing form, not a full finite verb.',
    example: 'Instead of translating every word, I explained the situation.',
    exampleZh: '我没有逐字翻译，而是解释了这个情境。',
    tryZh: '我没有责怪他，而是问他为什么这样想。',
    type: 'contrast_choice',
    level: 'junior',
    functions: ['contrast', 'choice'],
    risks: ['verb_form', 'literal_translation'],
  },
  {
    text: 'in spite of...',
    meaning: '尽管；虽然',
    usage: 'Used before a noun or -ing phrase to show contrast.',
    commonError: 'Do not put a full clause directly after in spite of unless using the fact that.',
    example: 'In spite of the misunderstanding, we kept the conversation friendly.',
    exampleZh: '尽管有误会，我们仍让谈话保持友好。',
    tryZh: '尽管有语言困难，我们还是完成了采访。',
    type: 'concession_phrase',
    level: 'senior',
    functions: ['concession', 'persistence'],
    risks: ['clause_after_preposition', 'preposition'],
  },
  {
    text: 'despite...',
    meaning: '尽管；虽然',
    usage: 'Used before a noun or -ing phrase; more concise than although.',
    commonError: 'Do not write “despite of”; despite already includes the preposition meaning.',
    example: 'Despite feeling nervous, I asked a follow-up question.',
    exampleZh: '尽管感到紧张，我还是追问了一个问题。',
    tryZh: '尽管时间很紧，我们还是认真听完了每个人的想法。',
    type: 'concession_phrase',
    level: 'senior',
    functions: ['concession', 'action'],
    risks: ['despite_of_error', 'verb_form'],
  },
  {
    text: 'It is not..., but...',
    meaning: '这不是……，而是……',
    usage: 'Used to reframe the meaning of a situation clearly.',
    commonError: 'Keep the two contrasted parts parallel.',
    example: 'It is not a failure, but a chance to learn how to communicate better.',
    exampleZh: '这不是失败，而是学习如何更好沟通的机会。',
    tryZh: '这不是简单的翻译问题，而是语气和文化背景的问题。',
    type: 'contrast_reframing',
    level: 'junior',
    functions: ['reframing', 'clarification'],
    risks: ['parallel_structure', 'logic'],
  },
  {
    text: 'What matters is not..., but...',
    meaning: '重要的不是……，而是……',
    usage: 'Used to shift attention from a surface point to the real value.',
    commonError: 'Avoid making the two parts vague; both sides should be clear.',
    example: 'What matters is not perfect pronunciation, but clear and respectful communication.',
    exampleZh: '重要的不是完美发音，而是清楚且尊重的交流。',
    tryZh: '重要的不是谁说得最多，而是谁真正理解了别人。',
    type: 'value_reframing',
    level: 'senior',
    functions: ['value_focus', 'reflection'],
    risks: ['parallel_structure', 'abstract_expression'],
  },
  {
    text: 'What I mean is...',
    meaning: '我的意思是……',
    usage: 'Used to clarify your point when the listener may misunderstand.',
    commonError: 'Do not use it as a filler too often; it should clarify a real point.',
    example: 'What I mean is that we should explain the reason before judging the habit.',
    exampleZh: '我的意思是，我们应该先解释原因，再评价这个习惯。',
    tryZh: '我的意思是，我们可以不同意，但仍然保持尊重。',
    type: 'communicative_expression',
    level: 'junior',
    functions: ['clarification', 'repair'],
    risks: ['overuse', 'clause_structure'],
  },
  {
    text: 'Let me put it another way.',
    meaning: '我换一种说法。',
    usage: 'Used to repair communication and make an idea easier to understand.',
    commonError: 'Use it before a clearer explanation, not as an empty sentence.',
    example: 'Let me put it another way. The custom is less about rules and more about care.',
    exampleZh: '我换一种说法。这个习俗与其说是规则，不如说是关心。',
    tryZh: '我换一种说法：AI 是工具，不是替你思考的人。',
    type: 'communicative_expression',
    level: 'junior',
    functions: ['clarification', 'repair'],
    risks: ['empty_phrase', 'tone'],
  },
  {
    text: 'It depends on...',
    meaning: '这取决于……',
    usage: 'Used to avoid oversimplifying an answer.',
    commonError: 'Do not answer every question with it; add what it depends on.',
    example: 'It depends on how the feedback is given.',
    exampleZh: '这取决于反馈是怎样给出的。',
    tryZh: '这取决于对方是否理解你的语气。',
    type: 'communicative_expression',
    level: 'junior',
    functions: ['nuance', 'explanation'],
    risks: ['incomplete_answer', 'preposition'],
  },
  {
    text: 'I used to think..., but now...',
    meaning: '我过去以为……，但现在……',
    usage: 'Used to show a clear change in understanding.',
    commonError: 'After used to, use the base verb; do not write used to thought.',
    example: 'I used to think silence meant agreement, but now I know it can mean respect.',
    exampleZh: '我过去以为沉默意味着同意，但现在我知道它也可能意味着尊重。',
    tryZh: '我过去以为直接表达最清楚，但现在我知道语气也很重要。',
    type: 'reflection_change',
    level: 'junior',
    functions: ['reflection', 'change'],
    risks: ['verb_form', 'tense'],
  },
  {
    text: "I didn't realize...until...",
    meaning: '直到……我才意识到……',
    usage: 'Used to show delayed realization.',
    commonError: 'Do not translate with “until” at the beginning awkwardly; keep the pattern clear.',
    example: "I didn't realize how nervous she was until she stopped speaking.",
    exampleZh: '直到她停下来不说话，我才意识到她有多紧张。',
    tryZh: '直到我看到他的表情，我才意识到自己的话太直接了。',
    type: 'realization_structure',
    level: 'senior',
    functions: ['realization', 'narrative_turn'],
    risks: ['until_structure', 'tense'],
  },
  {
    text: 'The reason why...is that...',
    meaning: '……的原因是……',
    usage: 'Used to explain a reason clearly and logically.',
    commonError: 'Avoid “the reason is because” in careful writing; use “is that”.',
    example: 'The reason why I explained it slowly is that I did not want him to feel judged.',
    exampleZh: '我慢慢解释的原因是，我不想让他觉得被评价。',
    tryZh: '我选择先倾听的原因是，我想真正理解他的感受。',
    type: 'reason_explanation',
    level: 'junior',
    functions: ['explanation', 'reasoning'],
    risks: ['reason_is_because', 'clause_structure'],
  },
  {
    text: 'What impressed me most was...',
    meaning: '最让我印象深刻的是……',
    usage: 'Used to highlight the most meaningful detail in an experience.',
    commonError: 'Do not write “what impressed me most is was”; keep the sentence tense consistent.',
    example: 'What impressed me most was how patiently she listened.',
    exampleZh: '最让我印象深刻的是她听得多么耐心。',
    tryZh: '最让我印象深刻的是他们愿意理解我们的习惯。',
    type: 'reflection_emphasis',
    level: 'junior',
    functions: ['reflection', 'emphasis'],
    risks: ['tense', 'clause_structure'],
  },
  {
    text: 'It turned out that...',
    meaning: '结果发现……；事实证明……',
    usage: 'Used to reveal an unexpected result or truth.',
    commonError: 'Do not overuse it for every result; use it when there is a change in expectation.',
    example: 'It turned out that the misunderstanding came from a small difference in tone.',
    exampleZh: '结果发现，这个误会来自语气上的一个小差异。',
    tryZh: '结果发现，他不是不礼貌，只是不知道该怎么拒绝。',
    type: 'narrative_revelation',
    level: 'junior',
    functions: ['narrative_turn', 'realization'],
    risks: ['overuse', 'tense'],
  },
  {
    text: 'This made me realize that...',
    meaning: '这让我意识到……',
    usage: 'Used to connect an experience with reflection.',
    commonError: 'Do not follow it with a fragment; use a full that-clause.',
    example: 'This made me realize that clear English also needs a respectful tone.',
    exampleZh: '这让我意识到，清楚的英语也需要尊重的语气。',
    tryZh: '这让我意识到，跨文化交流需要耐心和具体例子。',
    type: 'reflection_result',
    level: 'junior',
    functions: ['reflection', 'realization'],
    risks: ['fragment', 'abstract_expression'],
  },
]

function categoryFor(type: string) {
  if (type.includes('comparison')) return 'curated_high_value_comparison'
  if (type.includes('concession')) return 'curated_high_value_concession'
  if (type.includes('communicative')) return 'curated_high_value_communication'
  if (type.includes('negative') || type.includes('nothing')) return 'curated_high_value_negative_emphasis'
  if (type.includes('reflection') || type.includes('realization')) return 'curated_high_value_reflection'
  return 'curated_high_value_special'
}

async function main() {
  const [topics, goals] = await Promise.all([
    prisma.topic.findMany({ where: { active: true }, select: { id: true, label: true } }),
    prisma.writingGoal.findMany({ where: { active: true }, select: { id: true, label: true } }),
  ])

  for (let i = 0; i < seeds.length; i += 1) {
    const seed = seeds[i]
    const code = `HVC-${String(i + 1).padStart(3, '0')}`
    const row = await prisma.construction.upsert({
      where: { code },
      update: {
        name: seed.text,
        template: seed.text,
        coreWords: seed.text.replace(/\.\.\./g, '').trim(),
        function: seed.meaning,
        usageNote: seed.usage,
        example: seed.example,
        variants: null,
        difficulty: seed.level === 'senior' ? 'Senior High' : 'Junior High',
        level: seed.level,
        category: categoryFor(seed.type),
        metadataVersion: VERSION,
        rotationWeight: 1.45,
        metadata: {
          construction_type: seed.type,
          construction_text: seed.text,
          meaning_zh: seed.meaning,
          usage_note: seed.usage,
          common_error: seed.commonError,
          common_error_risk: seed.risks,
          example_sentence: seed.example,
          example_zh: seed.exampleZh,
          imitation_prompt_zh: seed.tryZh,
          recommended_exercise_types: ['construction_imitation', 'micro_continuation', 'short_continuation_50', 'long_continuation'],
          school_level: seed.level === 'senior' ? 'Senior High' : 'Junior High',
          fine_level: seed.level === 'senior' ? 'L4' : 'L3',
          communicative_function: seed.functions,
          emotional_function: seed.functions.filter((item) => ['emphasis', 'emotional_expression', 'encouragement', 'empathy', 'relief'].includes(item)),
          narrative_function: seed.functions.filter((item) => ['reflection', 'narrative_turn', 'realization', 'development'].includes(item)),
          interaction_type: ['peer_to_peer', 'local_to_foreigner', 'student_to_friend'],
          intercultural_value: ['clarifying_meaning', 'avoiding_misunderstanding', 'showing_respect', 'expressing_nuance'],
          scene_type: ['student_life', 'intercultural_communication', 'class_discussion'],
          production_difficulty: seed.level === 'senior' ? 'medium' : 'low',
          teaching_value: 'high',
          student_growth_value: 'high',
          teaching_priority: 'very_high',
          usage_frequency: 'high',
          use_in_generation: true,
          active_for_learning: true,
          vocabulary_only: false,
          curated_priority: 'core_high_value',
          quality_principle: 'frequent_confusing_high_leverage_expression',
          source: VERSION,
        },
      },
      create: {
        code,
        name: seed.text,
        template: seed.text,
        coreWords: seed.text.replace(/\.\.\./g, '').trim(),
        function: seed.meaning,
        usageNote: seed.usage,
        example: seed.example,
        difficulty: seed.level === 'senior' ? 'Senior High' : 'Junior High',
        level: seed.level,
        category: categoryFor(seed.type),
        metadataVersion: VERSION,
        rotationWeight: 1.45,
        metadata: {
          construction_type: seed.type,
          construction_text: seed.text,
          meaning_zh: seed.meaning,
          usage_note: seed.usage,
          common_error: seed.commonError,
          common_error_risk: seed.risks,
          example_sentence: seed.example,
          example_zh: seed.exampleZh,
          imitation_prompt_zh: seed.tryZh,
          recommended_exercise_types: ['construction_imitation', 'micro_continuation', 'short_continuation_50', 'long_continuation'],
          school_level: seed.level === 'senior' ? 'Senior High' : 'Junior High',
          fine_level: seed.level === 'senior' ? 'L4' : 'L3',
          communicative_function: seed.functions,
          emotional_function: seed.functions.filter((item) => ['emphasis', 'emotional_expression', 'encouragement', 'empathy', 'relief'].includes(item)),
          narrative_function: seed.functions.filter((item) => ['reflection', 'narrative_turn', 'realization', 'development'].includes(item)),
          interaction_type: ['peer_to_peer', 'local_to_foreigner', 'student_to_friend'],
          intercultural_value: ['clarifying_meaning', 'avoiding_misunderstanding', 'showing_respect', 'expressing_nuance'],
          scene_type: ['student_life', 'intercultural_communication', 'class_discussion'],
          production_difficulty: seed.level === 'senior' ? 'medium' : 'low',
          teaching_value: 'high',
          student_growth_value: 'high',
          teaching_priority: 'very_high',
          usage_frequency: 'high',
          use_in_generation: true,
          active_for_learning: true,
          vocabulary_only: false,
          curated_priority: 'core_high_value',
          quality_principle: 'frequent_confusing_high_leverage_expression',
          source: VERSION,
        },
      },
    })

    for (const topic of topics) {
      await prisma.constructionTopic.upsert({
        where: { constructionId_topicId: { constructionId: row.id, topicId: topic.id } },
        update: { relevanceScore: 0.86, reason: 'Core high-value expression usable across student-life communication.' },
        create: { constructionId: row.id, topicId: topic.id, relevanceScore: 0.86, reason: 'Core high-value expression usable across student-life communication.' },
      })
    }
    for (const goal of goals) {
      await prisma.constructionGoal.upsert({
        where: { constructionId_goalId: { constructionId: row.id, goalId: goal.id } },
        update: { relevanceScore: 0.9, reason: `Supports ${goal.label} through high-leverage expression control.` },
        create: { constructionId: row.id, goalId: goal.id, relevanceScore: 0.9, reason: `Supports ${goal.label} through high-leverage expression control.` },
      })
    }
    for (const exerciseType of ['construction_imitation', 'micro_continuation', 'short_continuation_50', 'long_continuation']) {
      await prisma.constructionExerciseType.upsert({
        where: { constructionId_exerciseType: { constructionId: row.id, exerciseType } },
        update: { relevanceScore: exerciseType === 'construction_imitation' ? 1 : 0.88, reason: 'Core high-value confusing construction.' },
        create: { constructionId: row.id, exerciseType, relevanceScore: exerciseType === 'construction_imitation' ? 1 : 0.88, reason: 'Core high-value confusing construction.' },
      })
    }
  }

  console.log(JSON.stringify({ version: VERSION, upserted: seeds.length }, null, 2))
}

main()
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
